### ISSUE TITLE
Ajustes na análise de desempenho e missões

### ISSUE THREAD

**Issue by EricksonFerreira** [RenissonSilva/improov#17]
Análise de desempenho
- [x] Colocar legenda do que significa o verde e vermelho
- [x] Definir metas (por exemplo, o ideal no grafico de missões concluidas ser 10, abaixo disso fica vermelho) e fazer a lógica
- [x] Adicionar o filtro, que traz os dados a partir de ( Diario, semanal, mensal, todos)
- [x] Guardar todos os dados da analise de desempenho no banco
- [x] Fazer com que o desempenho seja atualizado diariamente por uma cronjob

Melhorar sistema de missões

- [x] #20 
- [x] #21

Banner

- [x] #19
