### ISSUE TITLE
Sprint 8 - Melhoria nas missões, análise de desempenho e ajuste de bugs

### ISSUE THREAD

**Issue by RenissonSilva** [RenissonSilva/improov#22]
Geral
- [x] Resolver o bug ao iniciar, deve ser limite de requisição ou bug ao criar conta nova

Missões
- [x] Bug de missões duplicadas
- [x] #26
- [x] #25
- [x] Listar missões concluídas
- [x] Deixar funcional a cronjob de repetir missão
- [x] Ajustar tamanho modal ao deletar missão

Análise e desempenho
- [x] #33
- [x] #32
