### ISSUE TITLE
Criar back-end para análise de desempenho

### ISSUE THREAD

**Issue by EricksonFerreira** [RenissonSilva/improov#9]
Eu **como** desenvolvedor **quero** o funcionamento das atividades do back-end da análise de desempenho **para** fazer com que as informações sejam listadas na telas do front-end e adicionadas no banco de dados.

- [x] Analisar quantos controladores e métodos serão necessários.
- [x] Criar esses controladores e métodos.
- [x] Implementar os métodos.

**Comment by RenissonSilva** [comment]
Acabei enviando o back e front no mesmo commit, mas está funcional - [https://github.com/RenissonSilva/improov/commit/4d1d777d060c00e9b329ff73be6f28694e5c14ee](https://github.com/RenissonSilva/improov/commit/4d1d777d060c00e9b329ff73be6f28694e5c14ee)
